### ISSUE TITLE
Format numbers in the cards.jsx and sgCards.jsx with thousands seperator

### ISSUE THREAD

**Issue by thchong-code** [thchong-code/covid-dash#5]
Found out that the seperator attribute is not working despite  me specifying comma as seperator in Cards.jsx <CountUp />

Anyone knows the problem can give suggestions !

**Comment by imsamuel** [comment]
Just a minor spelling error! Use **separator** instead of seperator.

![image](https://user-images.githubusercontent.com/54451002/91090038-08c01180-e687-11ea-93dd-53476387e649.png)

**Comment by thchong-code** [comment]
#6
